export enum ConversationId {
  InstantSell = 'instantSell',
  Buy = 'buy',
  Sell = 'sell',
  Withdraw = 'withdraw',
  ExportPrivateKey = 'exportPrivateKey',
  CreateAftermathPool = 'createAftermathPool',
  CreateCetusPool = 'createCetusPool',
  AddCetusPoolLiquidity = 'addCetusPoolLiquidity',
  CreateCoin = 'createCoin',
  WelcomeBonus = 'welcomeBonus',
  ImportNewWallet = 'importNewWallet',
  CheckCurrentWalletForRefund = 'checkCurrentWalletForRefund',
  CheckProvidedAddressForRefund = 'checkProvidedAddressForRefund',
}
