export enum ConversationId {
  Buy = 'buy',
  Sell = 'sell',
  Withdraw = 'withdraw',
  ExportPrivateKey = 'exportPrivateKey',
  CreateAftermathPool = 'createAftermathPool',
  CreateCetusPool = 'createCetusPool',
  AddCetusPoolLiquidity = 'addCetusPoolLiquidity',
  CreateCoin = 'createCoin',
  CreateDca = 'createDca',
  DepositDcaBase = 'depositDcaBase',
  WithdrawDcaBase = 'withdrawDcaBase',
  IncreaseDcaOrders = 'increaseDcaOrders',
  CloseDca = 'closeDca',
  WelcomeBonus = 'welcomeBonus',
}
