export enum CallbackQueryData {
  Cancel = 'close-conversation',
  Confirm = 'confirm',
  Yes = 'yes',
  No = 'no',
  BaseRefund = 'base-refund',
  BoostedRefund = 'boosted-refund',
  Assets = 'assets',
  ExportPrivateKey = 'export-private-key',
  ImportWallet = 'import-wallet',
  Continue = 'continue',
  Refunds = 'refunds',
  RepeatSameBuy = 'repeat-same-buy',
  CoinWhitelist = 'coin-whitelist',
  Home = 'go-home',
}
