export enum CallbackQueryData {
  Cancel = 'close-conversation',
  Confirm = 'confirm',
  Yes = 'yes',
  No = 'no',
  BaseRefund = 'base-refund',
  BoostedRefund = 'boosted-refund',
  Assets = 'assets',
  ExportPrivateKey = 'export-private-key',
  ImportWallet = 'import-wallet',
  Continue = 'continue',
  Refunds = 'refunds',
  Skip = 'skip',
  ShowOwnedTurbosPools = 'show-owned-turbos-pools',
  CreateTurbosPool = 'create-turbos-pool',
  LoadDetailedPoolsInfo = 'load-detailed-pools-info',
}
